# COGS 118A Final Project Fall 2024

## Dataset 2: [Estimation of Obesity Levels Based On Eating Habits and Physical Condition](https://archive.ics.uci.edu/dataset/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition)


In [1]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
default_of_credit_card_clients = fetch_ucirepo(id=350)

dataset = default_of_credit_card_clients.data.original

dataset.head()

ID      X1  X2  X3  X4  X5  X6  X7  X8  X9  ...    X15    X16    X17   X18  \
0   1   20000   2   2   1  24   2   2  -1  -1  ...      0      0      0     0   
1   2  120000   2   2   2  26  -1   2   0   0  ...   3272   3455   3261     0   
2   3   90000   2   2   2  34   0   0   0   0  ...  14331  14948  15549  1518   
3   4   50000   2   2   1  37   0   0   0   0  ...  28314  28959  29547  2000   
4   5   50000   1   2   1  57  -1   0  -1   0  ...  20940  19146  19131  2000   

     X19    X20   X21   X22   X23  Y  
0    689      0     0     0     0  1  
1   1000   1000  1000     0  2000  1  
2   1500   1000  1000  1000  5000  0  
3   2019   1200  1100  1069  1000  0  
4  36681  10000  9000   689   679  0  

[5 rows x 25 columns]

In [3]:
dataset.shape

(30000, 25)

In [4]:
dataset.dtypes

ID     int64
X1     int64
X2     int64
X3     int64
X4     int64
X5     int64
X6     int64
X7     int64
X8     int64
X9     int64
X10    int64
X11    int64
X12    int64
X13    int64
X14    int64
X15    int64
X16    int64
X17    int64
X18    int64
X19    int64
X20    int64
X21    int64
X22    int64
X23    int64
Y      int64
dtype: object

In [5]:
dataset.isnull().sum()

ID     0
X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
X17    0
X18    0
X19    0
X20    0
X21    0
X22    0
X23    0
Y      0
dtype: int64

In [6]:
dataset.describe()

ID              X1            X2            X3            X4  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   167484.322667      1.603733      1.853133      1.551867   
std     8660.398374   129747.661567      0.489129      0.790349      0.521970   
min        1.000000    10000.000000      1.000000      0.000000      0.000000   
25%     7500.750000    50000.000000      1.000000      1.000000      1.000000   
50%    15000.500000   140000.000000      2.000000      2.000000      2.000000   
75%    22500.250000   240000.000000      2.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      6.000000      3.000000   

                 X5            X6            X7            X8            X9  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      35.485500     -0.016700     -0.133767     -0.166200     -0.220667   
std        9.217904      1.123802      1.197186      1.196868      1.169139   
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       34.000000      0.000000      0.000000      0.000000      0.000000   
75%       41.000000      0.000000      0.000000      0.000000      0.000000   
max       79.000000      8.000000      8.000000      8.000000      8.000000   

       ...            X15            X16            X17            X18  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000   
mean   ...   43262.948967   40311.400967   38871.760400    5663.580500   
std    ...   64332.856134   60797.155770   59554.107537   16563.280354   
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000   
25%    ...    2326.750000    1763.000000    1256.000000    1000.000000   
50%    ...   19052.000000   18104.500000   17071.000000    2100.000000   
75%    ...   54506.000000   50190.500000   49198.250000    5006.000000   
max    ...  891586.000000  927171.000000  961664.000000  873552.000000   

                X19           X20            X21            X22  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

                 X23             Y  
count   30000.000000  30000.000000  
mean     5215.502567      0.221200  
std     17777.465775      0.415062  
min         0.000000      0.000000  
25%       117.750000      0.000000  
50%      1500.000000      0.000000  
75%      4000.000000      0.000000  
max    528666.000000      1.000000  

[8 rows x 25 columns]

In [7]:
dataset['Y'].value_counts()

Y
0    23364
1     6636
Name: count, dtype: int64

# Pre Processing


In [8]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from tqdm import tqdm

In [9]:
# Separate features (X) and target (y)
X = dataset.drop(columns=['ID', 'Y'])
y = dataset['Y']

# Identify numeric and categorical columns
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object', 'category']).columns

# Preprocessing for numeric and categorical features
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [10]:
def comprehensive_model_evaluation(X, y, classifier, param_grid, split_ratios=[0.2, 0.5, 0.8]):
    """
    Comprehensive model evaluation across multiple splits and configurations
    """
    all_results = []

    for test_size in tqdm(split_ratios, desc="Split Ratios"):
        for seed in tqdm(range(3), desc="Random Seeds", leave=False):
            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=test_size, random_state=42 + seed)

            pipeline = Pipeline([
                ('preprocessor', preprocessor),
                ('classifier', classifier)
            ])

            grid_search = GridSearchCV(
                pipeline,
                param_grid,
                cv=5,
                scoring='accuracy',
                n_jobs=-1
            )
            grid_search.fit(X_train, y_train)

            best_model = grid_search.best_estimator_
            train_pred = best_model.predict(X_train)
            test_pred = best_model.predict(X_test)

            result = {
                'Test Size': f"{int((1-test_size)*100)}-{int(test_size*100)}",
                'Random Seed': seed,
                'Best Params': str(grid_search.best_params_),
                'Best CV Score': grid_search.best_score_,
                'Train Accuracy': accuracy_score(y_train, train_pred),
                'Test Accuracy': accuracy_score(y_test, test_pred),
                'Classifier': type(classifier).__name__
            }

            report = classification_report(y_test, test_pred, output_dict=True)
            result.update({
                'Macro Precision': report['macro avg']['precision'],
                'Macro Recall': report['macro avg']['recall'],
                'Macro F1-Score': report['macro avg']['f1-score']
            })

            # Add confusion matrix
            cm = confusion_matrix(y_test, test_pred)
            result['Confusion Matrix'] = cm

            all_results.append(result)

    results_df = pd.DataFrame(all_results)
    print("Evaluation Summary:")
    print(results_df.groupby(['Test Size', 'Classifier'])[
          ['Train Accuracy', 'Test Accuracy', 'Best CV Score']].agg(['mean', 'std']))

    # Optionally, you could print confusion matrices for all splits
    for result in all_results:
        print(f"Confusion Matrix for Test Size {
              result['Test Size']} and Seed {result['Random Seed']}:")
        print(result['Confusion Matrix'])

    return results_df

## Logistic Regression


In [12]:
lr_param_grid = {
    'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100],
    'classifier__penalty': ['l1', 'l2'],
    'classifier__solver': ['liblinear']
}

# Comprehensive evaluation
lr_results = comprehensive_model_evaluation(
    X, y,
    LogisticRegression(),
    lr_param_grid
)

lr_results

Split Ratios: 100%|██████████| 3/3 [00:18<00:00,  6.09s/it]

Evaluation Summary:
                             Train Accuracy           Test Accuracy            \
                                       mean       std          mean       std   
Test Size Classifier                                                            
19-80     LogisticRegression       0.809667  0.004851      0.810722  0.001425   
50-50     LogisticRegression       0.809600  0.002400      0.809756  0.000539   
80-20     LogisticRegression       0.810889  0.002234      0.809056  0.006571   

                             Best CV Score            
                                      mean       std  
Test Size Classifier                                  
19-80     LogisticRegression      0.807611  0.004276  
50-50     LogisticRegression      0.809267  0.002008  
80-20     LogisticRegression      0.810361  0.002189  
Confusion Matrix for Test Size 80-20 and Seed 0:
[[4554  133]
 [1006  307]]
Confusion Matrix for Test Size 80-20 and Seed 1:
[[4523  129]
 [1059  289]]
Confusion M

Test Size  Random Seed                                        Best Params  \
0     80-20            0  {'classifier__C': 0.1, 'classifier__penalty': ...   
1     80-20            1  {'classifier__C': 1, 'classifier__penalty': 'l...   
2     80-20            2  {'classifier__C': 0.1, 'classifier__penalty': ...   
3     50-50            0  {'classifier__C': 0.01, 'classifier__penalty':...   
4     50-50            1  {'classifier__C': 0.1, 'classifier__penalty': ...   
5     50-50            2  {'classifier__C': 1, 'classifier__penalty': 'l...   
6     19-80            0  {'classifier__C': 1, 'classifier__penalty': 'l...   
7     19-80            1  {'classifier__C': 10, 'classifier__penalty': '...   
8     19-80            2  {'classifier__C': 1, 'classifier__penalty': 'l...   

   Best CV Score  Train Accuracy  Test Accuracy          Classifier  \
0       0.810000        0.810500       0.810167  LogisticRegression   
1       0.812708        0.813292       0.802000  LogisticRegression   
2       0.808375        0.808875       0.815000  LogisticRegression   
3       0.807533        0.807200       0.810067  LogisticRegression   
4       0.811467        0.812000       0.809133  LogisticRegression   
5       0.808800        0.809600       0.810067  LogisticRegression   
6       0.804000        0.806000       0.809083  LogisticRegression   
7       0.806500        0.807833       0.811667  LogisticRegression   
8       0.812333        0.815167       0.811417  LogisticRegression   

   Macro Precision  Macro Recall  Macro F1-Score              Confusion Matrix  
0         0.758396      0.602720        0.619551    [[4554, 133], [1006, 307]]  
1         0.750835      0.593331        0.605605    [[4523, 129], [1059, 289]]  
2         0.784350      0.606680        0.625150    [[4580, 104], [1006, 310]]  
3         0.757232      0.601567        0.618086   [[11393, 332], [2517, 758]]  
4         0.758156      0.601315        0.617516   [[11377, 328], [2535, 760]]  
5         0.760116      0.606115        0.623785   [[11353, 340], [2509, 798]]  
6         0.774808      0.595551        0.609398  [[18289, 406], [4176, 1129]]  
7         0.758785      0.609312        0.628163  [[18170, 572], [3948, 1310]]  
8         0.766517      0.609280        0.627927  [[18164, 526], [4000, 1310]]

## KNN


In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
knn_param_grid = {
    # K from 1 to 104 with step 4
    'classifier__n_neighbors': np.arange(1, 105, 4),
    # 'uniform' or 'distance' weights
    'classifier__weights': ['uniform', 'distance'],
    'classifier__metric': ['euclidean', 'manhattan'],  # Distance metrics
}

# Assuming 'comprehensive_model_evaluation' is a function for evaluation
knn_results = comprehensive_model_evaluation(
    X, y,
    KNeighborsClassifier(),
    knn_param_grid
)

knn_results

Split Ratios: 100%|██████████| 3/3 [05:39<00:00, 113.26s/it]

Evaluation Summary:
                               Train Accuracy           Test Accuracy  \
                                         mean       std          mean   
Test Size Classifier                                                    
19-80     KNeighborsClassifier       0.808500  0.003041      0.807833   
50-50     KNeighborsClassifier       0.878244  0.105098      0.812289   
80-20     KNeighborsClassifier       0.879486  0.103899      0.810833   

                                         Best CV Score            
                                     std          mean       std  
Test Size Classifier                                              
19-80     KNeighborsClassifier  0.000855      0.803389  0.001711  
50-50     KNeighborsClassifier  0.000773      0.809933  0.001467  
80-20     KNeighborsClassifier  0.004604      0.811944  0.001295  
Confusion Matrix for Test Size 80-20 and Seed 0:
[[4459  228]
 [ 898  415]]
Confusion Matrix for Test Size 80-20 and Seed 1:
[[4421  231]
 

Test Size  Random Seed                                        Best Params  \
0     80-20            0  {'classifier__metric': 'euclidean', 'classifie...   
1     80-20            1  {'classifier__metric': 'euclidean', 'classifie...   
2     80-20            2  {'classifier__metric': 'euclidean', 'classifie...   
3     50-50            0  {'classifier__metric': 'euclidean', 'classifie...   
4     50-50            1  {'classifier__metric': 'euclidean', 'classifie...   
5     50-50            2  {'classifier__metric': 'euclidean', 'classifie...   
6     19-80            0  {'classifier__metric': 'euclidean', 'classifie...   
7     19-80            1  {'classifier__metric': 'euclidean', 'classifie...   
8     19-80            2  {'classifier__metric': 'euclidean', 'classifie...   

   Best CV Score  Train Accuracy  Test Accuracy            Classifier  \
0       0.811833        0.819792       0.812333  KNeighborsClassifier   
1       0.813292        0.999458       0.805667  KNeighborsClassifier   
2       0.810708        0.819208       0.814500  KNeighborsClassifier   
3       0.808467        0.999600       0.811400  KNeighborsClassifier   
4       0.811400        0.818067       0.812800  KNeighborsClassifier   
5       0.809933        0.817067       0.812667  KNeighborsClassifier   
6       0.803833        0.812000       0.806958  KNeighborsClassifier   
7       0.801500        0.807000       0.808667  KNeighborsClassifier   
8       0.804833        0.806500       0.807875  KNeighborsClassifier   

   Macro Precision  Macro Recall  Macro F1-Score              Confusion Matrix  
0         0.738890      0.633712        0.656114     [[4459, 228], [898, 415]]  
1         0.733367      0.628362        0.649076     [[4421, 231], [935, 413]]  
2         0.745762      0.636957        0.660224     [[4465, 219], [894, 422]]  
3         0.735288      0.632238        0.654233  [[11142, 583], [2246, 1029]]  
4         0.741838      0.634956        0.657646  [[11145, 560], [2248, 1047]]  
5         0.745631      0.631746        0.654329  [[11171, 522], [2288, 1019]]  
6         0.738403      0.613966        0.633018  [[17945, 750], [3883, 1422]]  
7         0.735846      0.618612        0.638743  [[17934, 808], [3784, 1474]]  
8         0.747989      0.609096        0.627238  [[18048, 642], [3969, 1341]]

## Decision Tree


In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
dt_param_grid = {
    # Maximum depth of the tree
    'classifier__max_depth': [None, 5, 10, 20, 30],
    # Minimum number of samples required to split a node
    'classifier__min_samples_split': [2, 5, 10],
    # Minimum number of samples required to be at a leaf node
    'classifier__min_samples_leaf': [1, 2, 4],
    # The function to measure the quality of a split
    'classifier__criterion': ['gini', 'entropy'],
    # Strategy used to split at each node
    'classifier__splitter': ['best', 'random'],
    # The number of features to consider for the best split
    'classifier__max_features': [None, 'sqrt', 'log2']
}

# Model evaluation using comprehensive_model_evaluation
dt_results = comprehensive_model_evaluation(
    X, y,
    DecisionTreeClassifier(),
    dt_param_grid
)

dt_results

Split Ratios: 100%|██████████| 3/3 [03:17<00:00, 65.67s/it] 

Evaluation Summary:
                                 Train Accuracy           Test Accuracy  \
                                           mean       std          mean   
Test Size Classifier                                                      
19-80     DecisionTreeClassifier       0.822944  0.005779      0.816486   
50-50     DecisionTreeClassifier       0.822044  0.004924      0.820489   
80-20     DecisionTreeClassifier       0.824889  0.001983      0.818111   

                                           Best CV Score            
                                       std          mean       std  
Test Size Classifier                                                
19-80     DecisionTreeClassifier  0.001936      0.815278  0.004097  
50-50     DecisionTreeClassifier  0.001535      0.818933  0.002821  
80-20     DecisionTreeClassifier  0.005165      0.820875  0.002521  
Confusion Matrix for Test Size 80-20 and Seed 0:
[[4432  255]
 [ 830  483]]
Confusion Matrix for Test Size 80-20 an

Test Size  Random Seed                                        Best Params  \
0     80-20            0  {'classifier__criterion': 'gini', 'classifier_...   
1     80-20            1  {'classifier__criterion': 'entropy', 'classifi...   
2     80-20            2  {'classifier__criterion': 'gini', 'classifier_...   
3     50-50            0  {'classifier__criterion': 'gini', 'classifier_...   
4     50-50            1  {'classifier__criterion': 'entropy', 'classifi...   
5     50-50            2  {'classifier__criterion': 'entropy', 'classifi...   
6     19-80            0  {'classifier__criterion': 'entropy', 'classifi...   
7     19-80            1  {'classifier__criterion': 'gini', 'classifier_...   
8     19-80            2  {'classifier__criterion': 'gini', 'classifier_...   

   Best CV Score  Train Accuracy  Test Accuracy              Classifier  \
0       0.820833        0.825375       0.819167  DecisionTreeClassifier   
1       0.823417        0.826583       0.812500  DecisionTreeClassifier   
2       0.818375        0.822708       0.822667  DecisionTreeClassifier   
3       0.815933        0.816867       0.821800  DecisionTreeClassifier   
4       0.821533        0.826667       0.820867  DecisionTreeClassifier   
5       0.819333        0.822600       0.818800  DecisionTreeClassifier   
6       0.813167        0.824667       0.818083  DecisionTreeClassifier   
7       0.812667        0.816500       0.814333  DecisionTreeClassifier   
8       0.820000        0.827667       0.817042  DecisionTreeClassifier   

   Macro Precision  Macro Recall  Macro F1-Score  \
0         0.748368      0.656727        0.680967   
1         0.746259      0.645150        0.668435   
2         0.760563      0.657213        0.683077   
3         0.760896      0.649343        0.675117   
4         0.755930      0.656152        0.681369   
5         0.758029      0.645656        0.670669   
6         0.752968      0.651079        0.675718   
7         0.736569      0.652274        0.674887   
8         0.757735      0.640328        0.664777   

                Confusion Matrix  
0      [[4432, 255], [830, 483]]  
1      [[4415, 237], [888, 460]]  
2      [[4459, 225], [839, 477]]  
3   [[11203, 522], [2151, 1124]]  
4   [[11119, 586], [2101, 1194]]  
5   [[11171, 522], [2196, 1111]]  
6   [[17768, 927], [3439, 1866]]  
7  [[17631, 1111], [3345, 1913]]  
8   [[17892, 798], [3593, 1717]]

## Bagging Classifier


In [17]:
from sklearn.ensemble import BaggingClassifier

In [19]:
bagging_param_grid = {
    # Reduce the number of estimators to speed up training while maintaining diversity
    'classifier__n_estimators': [10, 50],
    # Use a fixed smaller proportion of samples for training each estimator
    'classifier__max_samples': [0.5],
    # Limit the proportion of features considered for training each estimator
    'classifier__max_features': [0.7],
    # Use bootstrap sampling for diversity but fix its setting to avoid extra complexity
    'classifier__bootstrap': [True],
    # Base estimator remains a Decision Tree, but you can simplify the tree depth
    'classifier__estimator': [
        DecisionTreeClassifier(random_state=42, max_depth=10)
    ],
    'classifier__random_state': [42]  # Keep reproducibility
}

# Model evaluation using comprehensive_model_evaluation
bagging_results = comprehensive_model_evaluation(
    X, y,
    BaggingClassifier(),
    bagging_param_grid
)

Split Ratios: 100%|██████████| 3/3 [00:57<00:00, 19.15s/it]

Evaluation Summary:
                            Train Accuracy           Test Accuracy            \
                                      mean       std          mean       std   
Test Size Classifier                                                           
19-80     BaggingClassifier       0.875000  0.001202      0.815944  0.000487   
50-50     BaggingClassifier       0.860911  0.001201      0.818733  0.001328   
80-20     BaggingClassifier       0.855250  0.001187      0.818333  0.006764   

                            Best CV Score            
                                     mean       std  
Test Size Classifier                                 
19-80     BaggingClassifier      0.811333  0.003403  
50-50     BaggingClassifier      0.816333  0.003604  
80-20     BaggingClassifier      0.819250  0.001064  
Confusion Matrix for Test Size 80-20 and Seed 0:
[[4464  223]
 [ 864  449]]
Confusion Matrix for Test Size 80-20 and Seed 1:
[[4442  210]
 [ 922  426]]
Confusion Matrix for Te

In [20]:
bagging_results

Test Size  Random Seed                                        Best Params  \
0     80-20            0  {'classifier__bootstrap': True, 'classifier__e...   
1     80-20            1  {'classifier__bootstrap': True, 'classifier__e...   
2     80-20            2  {'classifier__bootstrap': True, 'classifier__e...   
3     50-50            0  {'classifier__bootstrap': True, 'classifier__e...   
4     50-50            1  {'classifier__bootstrap': True, 'classifier__e...   
5     50-50            2  {'classifier__bootstrap': True, 'classifier__e...   
6     19-80            0  {'classifier__bootstrap': True, 'classifier__e...   
7     19-80            1  {'classifier__bootstrap': True, 'classifier__e...   
8     19-80            2  {'classifier__bootstrap': True, 'classifier__e...   

   Best CV Score  Train Accuracy  Test Accuracy         Classifier  \
0       0.819000        0.855500       0.818833  BaggingClassifier   
1       0.820417        0.856292       0.811333  BaggingClassifier   
2       0.818333        0.853958       0.824833  BaggingClassifier   
3       0.812467        0.859533       0.820267  BaggingClassifier   
4       0.819600        0.861733       0.817933  BaggingClassifier   
5       0.816933        0.861467       0.818000  BaggingClassifier   
6       0.808667        0.875333       0.815417  BaggingClassifier   
7       0.810167        0.876000       0.816375  BaggingClassifier   
8       0.815167        0.873667       0.816042  BaggingClassifier   

   Macro Precision  Macro Recall  Macro F1-Score  \
0         0.752996      0.647193        0.671928   
1         0.748962      0.635441        0.658208   
2         0.769868      0.655322        0.682280   
3         0.754095      0.651223        0.676273   
4         0.751055      0.648385        0.672855   
5         0.751645      0.650673        0.675199   
6         0.754176      0.636339        0.660083   
7         0.743399      0.650639        0.674242   
8         0.756200      0.637529        0.661549   

                Confusion Matrix  
0      [[4464, 223], [864, 449]]  
1      [[4442, 210], [922, 426]]  
2      [[4484, 200], [851, 465]]  
3   [[11154, 571], [2125, 1150]]  
4   [[11129, 576], [2155, 1140]]  
5   [[11108, 585], [2145, 1162]]  
6   [[17897, 798], [3632, 1673]]  
7  [[17723, 1019], [3388, 1870]]  
8   [[17900, 790], [3625, 1685]]

## Random Forest


In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
rf_param_grid = {
    # Use a smaller set of estimators, keeping computational cost manageable
    'classifier__n_estimators': [100, 200],
    # Focus on a smaller range of max_features for efficiency
    'classifier__max_features': [4, 8, 12],
    # Fix random_state for reproducibility
    'classifier__random_state': [42]
}

# Model evaluation using comprehensive_model_evaluation
rf_results = comprehensive_model_evaluation(
    X, y,
    RandomForestClassifier(),
    rf_param_grid
)

rf_results

Split Ratios: 100%|██████████| 3/3 [08:24<00:00, 168.27s/it]

Evaluation Summary:
                                 Train Accuracy           Test Accuracy  \
                                           mean       std          mean   
Test Size Classifier                                                      
19-80     RandomForestClassifier       0.999722  0.000096      0.812875   
50-50     RandomForestClassifier       0.999489  0.000139      0.817800   
80-20     RandomForestClassifier       0.999431  0.000024      0.815611   

                                           Best CV Score            
                                       std          mean       std  
Test Size Classifier                                                
19-80     RandomForestClassifier  0.002542      0.811222  0.002335  
50-50     RandomForestClassifier  0.001988      0.816311  0.002837  
80-20     RandomForestClassifier  0.005419      0.817500  0.001057  
Confusion Matrix for Test Size 80-20 and Seed 0:
[[4415  272]
 [ 841  472]]
Confusion Matrix for Test Size 80-20 an

Test Size  Random Seed                                        Best Params  \
0     80-20            0  {'classifier__max_features': 12, 'classifier__...   
1     80-20            1  {'classifier__max_features': 8, 'classifier__n...   
2     80-20            2  {'classifier__max_features': 12, 'classifier__...   
3     50-50            0  {'classifier__max_features': 4, 'classifier__n...   
4     50-50            1  {'classifier__max_features': 8, 'classifier__n...   
5     50-50            2  {'classifier__max_features': 4, 'classifier__n...   
6     19-80            0  {'classifier__max_features': 12, 'classifier__...   
7     19-80            1  {'classifier__max_features': 4, 'classifier__n...   
8     19-80            2  {'classifier__max_features': 12, 'classifier__...   

   Best CV Score  Train Accuracy  Test Accuracy              Classifier  \
0       0.817042        0.999417       0.814500  RandomForestClassifier   
1       0.818708        0.999458       0.810833  RandomForestClassifier   
2       0.816750        0.999417       0.821500  RandomForestClassifier   
3       0.813400        0.999600       0.819933  RandomForestClassifier   
4       0.819067        0.999333       0.817467  RandomForestClassifier   
5       0.816467        0.999533       0.816000  RandomForestClassifier   
6       0.809333        0.999667       0.812875  RandomForestClassifier   
7       0.810500        0.999667       0.815417  RandomForestClassifier   
8       0.813833        0.999833       0.810333  RandomForestClassifier   

   Macro Precision  Macro Recall  Macro F1-Score  \
0         0.737200      0.650725        0.673491   
1         0.739183      0.648290        0.670831   
2         0.752463      0.664388        0.688921   
3         0.747740      0.660582        0.684633   
4         0.744855      0.656808        0.680460   
5         0.741190      0.658932        0.681862   
6         0.738209      0.647668        0.670409   
7         0.736924      0.659262        0.681568   
8         0.731424      0.647076        0.668895   

                Confusion Matrix  
0      [[4415, 272], [841, 472]]  
1      [[4389, 263], [872, 476]]  
2      [[4423, 261], [810, 506]]  
3   [[11062, 663], [2038, 1237]]  
4   [[11042, 663], [2075, 1220]]  
5   [[10990, 703], [2057, 1250]]  
6  [[17644, 1051], [3440, 1865]]  
7  [[17565, 1177], [3253, 2005]]  
8  [[17567, 1123], [3429, 1881]]

In [1]:
combined_results = pd.concat([
    lr_results,
    knn_results,
    dt_results,
    bagging_results,
    rf_results
])

# Aggregate and compare key metrics
comparison_summary = combined_results.groupby('Classifier')[
    ['Test Accuracy', 'Macro F1-Score', 'Best CV Score']
].agg(['mean', 'std'])

NameError: name 'pd' is not defined